export const BaseURL = "https://apartment-manager.uksouth.cloudapp.azure.com/"
export const GetAll = "/apartmentManager/getApartmentManager"
export const GetByID = "/apartmentManager/getApartmentManagerByID"
export const CreateApt = "/apartmentManager/createApartmentManager"
export const DeleteApt = "/apartmentManager/deleteApartmentManager"
export const UpdateApt = "/apartmentManager/updateApartmentManager"
export const CheckUser = "/verify/verifyPassword"
export const ColourGen = "/colourGen/getColour"